<a href="https://colab.research.google.com/github/FernandoCerriteno/Portafolio-TC3007C.502/blob/main/Deep%20Learning/RedNeuronalWords.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import io
import os
import re
import shutil
import string
import tensorflow as tf

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D
from tensorflow.keras.layers import TextVectorization

Importar IMDB dataset

In [ ]:
url = 'https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz'

dataset=tf.keras.utils.get_file("aclImdb.tar.gz", url,
                                untar=True,  cache_dir='.',
                                cache_subdir='')

dataset_dir=os.path.join(os.path.dirname(dataset), 'aclImdb')
os.listdir(dataset_dir)

84125825/84125825 [==============================] - 2s 0us/step


['README', 'imdbEr.txt', 'test', 'train', 'imdb.vocab']

In [ ]:
train_dir = os.path.join(dataset_dir, 'train')
remove_dir = os.path.join(train_dir, 'unsup')
shutil.rmtree(remove_dir)

Crear Dataset

In [ ]:
batch_size = 1024
seed = 123

train_ds = tf.keras.utils.text_dataset_from_directory(
    'aclImdb/train', batch_size=batch_size, validation_split=0.2,
    subset='training', seed=seed)

val_ds = tf.keras.utils.text_dataset_from_directory(
    'aclImdb/train', batch_size=batch_size, validation_split=0.2,
    subset='validation', seed=seed)


Found 25000 files belonging to 2 classes.
Using 20000 files for training.
Found 25000 files belonging to 2 classes.
Using 5000 files for validation.


In [ ]:
for text_batch, label_batch in train_ds.take(1):
  for i in range(5):
    print(label_batch[i].numpy(), text_batch.numpy()[i])

0 b"Oh My God! Please, for the love of all that is holy, Do Not Watch This Movie! It it 82 minutes of my life I will never get back. Sure, I could have stopped watching half way through. But I thought it might get better. It Didn't. Anyone who actually enjoyed this movie is one seriously sick and twisted individual. No wonder us Australians/New Zealanders have a terrible reputation when it comes to making movies. Everything about this movie is horrible, from the acting to the editing. I don't even normally write reviews on here, but in this case I'll make an exception. I only wish someone had of warned me before I hired this catastrophe"
1 b'This movie is SOOOO funny!!! The acting is WONDERFUL, the Ramones are sexy, the jokes are subtle, and the plot is just what every high schooler dreams of doing to his/her school. I absolutely loved the soundtrack as well as the carefully placed cynicism. If you like monty python, You will love this film. This movie is a tad bit "grease"esk (without

In [ ]:
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

<h3>Capa Text Embedding

In [ ]:
embedding_layer = tf.keras.layers.Embedding(1000,5)
result = embedding_layer(tf.constant([1,2,3]))
print(result.numpy())

[[ 0.03987518 -0.0088542   0.04803034  0.03799907  0.02152473]
 [-0.01932117  0.01562719 -0.04690391 -0.04961808  0.01984718]
 [ 0.04795258 -0.01169391 -0.01725074  0.02629668  0.02587852]]


In [ ]:
print(result.shape)

(3, 5)


Preprocesamiento del texto

In [ ]:
from tensorflow.python.ops.parallel_for.control_flow_ops import vectorized_map
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html, '[%s]' % re.escape(string.punctuation), '')

vocab_size = 10000
sequence_length = 100

vectorize_layer = TextVectorization(
    standardize = custom_standardization,
    max_tokens = vocab_size,
    output_mode = 'int',
    output_sequence_length = sequence_length)

text_ds = train_ds.map(lambda x, y:x)
vectorize_layer.adapt(text_ds)

Crear modelo de clasificación

In [ ]:
embedding_dim = 16
model = Sequential([
    vectorize_layer,
    Embedding(vocab_size, embedding_dim, name='embedding'),
    GlobalAveragePooling1D(),
    Dense(10,activation='relu'),
    Dense(1)
])

In [ ]:
model.compile(optimizer='Adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15
)

Epoch 1/15
20/20 [==============================] - 5s 193ms/step - loss: 0.6918 - accuracy: 0.5028 - val_loss: 0.6893 - val_accuracy: 0.4886
Epoch 2/15
20/20 [==============================] - 2s 88ms/step - loss: 0.6861 - accuracy: 0.5028 - val_loss: 0.6824 - val_accuracy: 0.4886
Epoch 3/15
20/20 [==============================] - 2s 90ms/step - loss: 0.6771 - accuracy: 0.5028 - val_loss: 0.6714 - val_accuracy: 0.4886
Epoch 4/15
20/20 [==============================] - 2s 87ms/step - loss: 0.6634 - accuracy: 0.5028 - val_loss: 0.6563 - val_accuracy: 0.4886
Epoch 5/15
20/20 [==============================] - 2s 100ms/step - loss: 0.6448 - accuracy: 0.5028 - val_loss: 0.6368 - val_accuracy: 0.4886
Epoch 6/15
20/20 [==============================] - 3s 165ms/step - loss: 0.6216 - accuracy: 0.5181 - val_loss: 0.6136 - val_accuracy: 0.5362
Epoch 7/15
20/20 [==============================] - 2s 83ms/step - loss: 0.5944 - accuracy: 0.5871 - val_loss: 0.5880 - val_accuracy: 0.6010
Epoch 8/15

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 text_vectorization_3 (Text  (None, 100)               0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 100, 16)           160000    
                                                                 
 global_average_pooling1d (  (None, 16)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 10)                170       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 160181 (625.71 KB)
Trainable params: 16018

Descarga de los datos

In [ ]:
weights=model.get_layer('embedding').get_weights()[0]
vocab = vectorize_layer.get_vocabulary()

out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

for index,word in enumerate(vocab):
  if index == 0:
    continue
  vec = weights[index]
  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
  out_m.write(word + "\n")

out_v.close()
out_m.close()